Remove dependency on node-gyp
node-gyp needs to be installed on the machine before this module can be
installed. This fixes issues on CentOS where the yum-installed node-gyp works
fine, but the npm-installed node-gyp dies with

Traceback (most recent call last):
  File "/repos/sse4_crc32/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
AttributeError: 'module' object has no attribute 'script_main'